substitutions:
  devicename: spore-sensor-ths-co2-1
  friendly_name: Temp and Humidity and CO2 Sensor
  device_description: Detect Temp/Humidity/CO2 with SCD41 Sensor

esphome:
  name: $devicename
  comment: ${device_description}
  name_add_mac_suffix: true

i2c:
  frequency: 150000.0