substitutions:
  devicename: thermocouple-1
  friendly_name: Thermocouple Sensor
  device_description: Detect Temperature with Thermocouple Sensor



esphome:
  name: $devicename
  comment: ${device_description}
