{
 "title": "Tester's Farm",
 "time": { "from": "now-18h", "to": "now" },
 "panels": [
  {
   "title": "Tester's Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "avg_over_time(esphome_sensor_value{job=\"spore-sensors\", location=\"test_farm_hau5\", instance=\"192.168.1.112:6969\", name=\"SCD41 Temperature\"}[15m]) * 1.8 + 32",
     "legendFormat": "__auto"
    },
    {
     "expr": "esphome_sensor_value{job=\"spore-sensors\", location=\"test_farm_hau5\", instance=\"192.168.1.108:6969\", name=\"SHT4X Temperature\"} * 1.8 + 32",
     "legendFormat": "__auto"
    },
    {
     "expr": "esphome_sensor_value{job=\"spore-sensors\", location=\"test_farm_hau5\", instance=\"192.168.1.109:6969\", name=\"SHT4X Temperature\"} * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tester's Humidity",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n    avg_over_time(esphome_sensor_value{job=\"spore-sensors\",\n    location=\"test_farm_hau5\",\n    instance=\"192.168.1.112:6969\", name=\"SCD41 Humidity\"}[5m]),\n    \"display_name\",\n    \"$1 - $2 (Avg 5m)\",\n    \"location,name\",\n    \"(.*)_(.*)\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    avg_over_time(esphome_sensor_value{job=\"spore-sensors\", location=\"test_farm_hau5\", instance=\"192.168.1.108:6969\", name=\"SHT4x Humidity\"}[5m]),\n  \"display_name\",\n  \"$1 - $2 (Avg 5m)\",\n  \"location,name\",\n  \"(.*)_(.*)\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(esphome_sensor_value{job=\"spore-sensors\", location=\"test_farm_hau5\", instance=\"192.168.1.109:6969\", name=\"SHT4x Humidity\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tester's CO2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{job=\"spore-sensors\", location=\"test_farm_hau5\", instance=\"192.168.1.112:6969\", name=\"SCD41 CO2\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}