esphome:
  name: ths-1

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "test1234"

ota:
  password: "test1234"

wifi:
  ssid: "my_wifi_ssid"
  password: "my_wifi_password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ths-1 Fallback Hotspot"
    password: "example_fallback_password"

captive_portal:


# Configure I2C
i2c:
  sda: 6  # Adjust to your SDA pin
  scl: 5  # Adjust to your SCL pin
  scan: True  # Scans for I2C devices at startup


# Configure the AM2301B sensor (using AHT10 protocol)
sensor:
  - platform: aht10
    temperature:
      name: "AM2301B Temperature"
      # id: temperature_sensor
    humidity:
      name: "AM2301B Humidity"
      # id: humidity_sensor
    update_interval: 10s
  - platform: scd4x
    co2:
      name: "SCD41 CO2"
    temperature:
      name: "SCD41 Temperature"
    humidity:
      name: "SCD41 Humidity"
    update_interval: 10s


web_server:
  port: 6969

prometheus:
